#pragma once

#define MAX_SPEED 2000
#define ACCELERATION 1500

// MAGNETIC LIMIT SWITCHES
#define LEFT_LIMIT_SW_PIN 10
#define RIGHT_LIMIT_SW_PIN 11

#define POLAR_Y_MIN_LIMIT (-285)
#define POLAR_X_MIN_LIMIT (-280)
#define POLAR_Y_MAX_LIMIT 300
#define POLAR_X_MAX_LIMIT 280

// #define POLAR_LEFT_HOME 500
// #define POLAR_RIGHT_HOME 500
// #define DIST_BETWEEN_MOTORS 800

/**
 * FROM OLD CODE */ 


// SYSTEM CONFIGURATIONS
#define LEFT_STEPS_PER_MM (12.5)
#define RIGHT_STEPS_PER_MM (12.5)

#define LEFT_STRIP_INIT_MAX_LENGTH_MM 1100
#define RIGHT_STRIP_INIT_MAX_LENGTH_MM 1100

#define RIGHT_STRIP_MIN_LENGTH_MM 100
#define LEFT_STRIP_MIN_LENGTH_MM 100
#define RIGHT_STRIP_MAX_LENGTH_MM 1000
#define LEFT_STRIP_MAX_LENGTH_MM 1000


#define MOTORS_DISTANCE (850)  // MM distance between the motors
#define X_OFFSET (-425)        // offset for the cartesian coortdinates system
#define Y_OFFSET (-410)

// BOUNDING BOX FOR THE CARTESIAN COORDINATE SYSTEM
#define MAX_X_VALUE (280)
#define MAX_Y_VALUE (300)
#define MIN_X_VALUE (-280)
#define MIN_Y_VALUE (-285)

