#pragma once

#define MAX_SPEED 2000
#define ACCELERATION 1500

// MAGNETIC LIMIT SWITCHES
#define LEFT_LIMIT_SW_PIN 10
#define RIGHT_LIMIT_SW_PIN 11

#define POLAR_Y_MIN_LIMIT (200)
#define POLAR_X_MIN_LIMIT (100)
#define POLAR_Y_MAX_LIMIT 1200
#define POLAR_X_MAX_LIMIT 1530

#define POLAR_LEFT_HOME 500
#define POLAR_RIGHT_HOME 500
#define DIST_BETWEEN_MOTORS 800

